'use strict';
const assert = require('assert');
const os = require('os');
const path = require('path');
const fs = require('fs');

const naming = require('../src/naming');
const { decide, SKIP } = require('../src/policy');
const { Store } = require('../src/state');
const { Namer, leadAgent, gitInfo, gitCache, detectProject,
  repoNameFromUrl, manifestName } = require('../src/namer');
const { planOrder, isClaimed } = require('../src/grouping');
const { isUselessCwd } = require('../src/namer');
const config = require('../src/config');

let passed = 0;
let failed = 0;
// Async tests were fired off unawaited and reported from a fixed timer, so a
// slow one could be cut off while the run still printed "0 failed".
const pending = [];
function test(name, fn) {
  try { fn(); passed += 1; process.stdout.write('  ok   ' + name + '\n'); }
  catch (err) { failed += 1; process.stdout.write('  FAIL ' + name + '\n       ' + err.message + '\n'); }
}
function testAsync(name, fn) {
  pending.push(Promise.resolve().then(fn).then(
    () => { passed += 1; process.stdout.write('  ok   ' + name + '\n'); },
    (err) => { failed += 1; process.stdout.write('  FAIL ' + name + '\n       ' + err.message + '\n'); },
  ));
}

function freshStore() {
  const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'mn-')), 'state.json');
  return new Store(file);
}
// Never config.load(): that reads the developer's installed config, so a tuned
// similarityThreshold would fail these tests for reasons unrelated to a change.
const cfg = (over = {}) => config.deepMerge(config.DEFAULTS, over);

process.stdout.write('\nnaming\n');
test('slugify fits herdr agent-name rules', () => {
  const s = naming.slugify('Herdr session naming plugin');
  assert.match(s, /^[a-z][a-z0-9_-]{0,31}$/);
  assert.strictEqual(s, 'herdr-session-naming-plugin');
});
test('slugify prefixes a leading digit', () => {
  assert.match(naming.slugify('3 failing tests'), /^[a-z]/);
});
test('slugify truncates on a word boundary', () => {
  const s = naming.slugify('Refactor the authentication middleware and session layer');
  assert.ok(s.length <= 32, 'length ' + s.length);
  assert.ok(!s.endsWith('-'));
});
test('normalize strips the agent state glyph', () => {
  assert.strictEqual(naming.normalize('◐ Herdr session naming plugin'), 'Herdr session naming plugin');
  assert.strictEqual(naming.normalize('✳ Astro docs site'), 'Astro docs site');
});
test('similarity treats rewordings as the same intent', () => {
  assert.ok(naming.similarity('rename tmux window', 'renaming tmux windows') >= 0.9);
  assert.ok(naming.similarity('Herdr naming plugin', 'Herdr naming plugins') >= 0.9);
});
test('similarity separates unrelated intents', () => {
  assert.ok(naming.similarity('Herdr naming plugin', 'Postgres index tuning') < 0.2);
});
test('looksAutoGenerated recognises herdr defaults', () => {
  assert.ok(naming.looksAutoGenerated('unifont', { repo: 'unifont' }));
  assert.ok(naming.looksAutoGenerated('w3'));
  assert.ok(naming.looksAutoGenerated('tab 2'));
  assert.ok(naming.looksAutoGenerated(''));
  assert.ok(!naming.looksAutoGenerated('code quality', { repo: 'unifont' }));
});
test('uniqueAgentName avoids collisions and stays in range', () => {
  const n = naming.uniqueAgentName('fix-auth', new Set(['fix-auth']));
  assert.strictEqual(n, 'fix-auth-2');
  const long = naming.uniqueAgentName('a'.repeat(32), new Set(['a'.repeat(32)]));
  assert.ok(long.length <= 32);
});
test('isJunkTitle rejects paths, shells and the bare repo name', () => {
  const c = cfg();
  assert.ok(naming.isJunkTitle('~/Code/foo', c));
  assert.ok(naming.isJunkTitle('zsh', c));
  assert.ok(naming.isJunkTitle('unifont', c, { repo: 'unifont' }));
  assert.ok(!naming.isJunkTitle('Fix auth middleware', c));
});
test('isJunkTitle rejects shell prompts and typed commands', () => {
  const c = cfg();
  // All observed live in the herdr pane.updated stream before an agent starts.
  for (const t of ['oddurs@host:~/Code/perfect', 'cd namesync',
    'claude --dangerously-skip-permissions', 'Claude Code', 'git status']) {
    assert.ok(naming.isJunkTitle(t, c), 'should be junk: ' + t);
  }
});
test('isJunkTitle keeps real intents, including tool-named ones', () => {
  const c = cfg();
  for (const t of ['Herdr session naming plugin', 'Open source wifi e-reader',
    'ptop-adopt-remaining-lessons', 'Linux system monitor tool',
    'Fix parser - a big job', 'Apple Notes-style Obsidian app']) {
    assert.ok(!naming.isJunkTitle(t, c), 'should be intent: ' + t);
  }
});
test('render fills template tokens', () => {
  assert.strictEqual(naming.render('{repo} - {intent}', { repo: 'app', intent: 'Fix auth' }), 'app - Fix auth');
});

process.stdout.write('\npolicy\n');
const base = (store, over = {}) => ({
  kind: 'workspace', id: 'w1', cfg: cfg(), store,
  agentStatus: 'working', context: { repo: 'unifont', dirName: 'unifont' },
  current: 'unifont', desired: 'Fix auth middleware', intent: 'Fix auth middleware',
  ...over,
});

test('adopts a workspace still using herdr default label', () => {
  assert.strictEqual(decide(base(freshStore())).rename, true);
});
test('never overwrites a hand-written name, and locks it', () => {
  const r = decide(base(freshStore(), { current: 'code quality' }));
  assert.strictEqual(r.rename, false);
  assert.strictEqual(r.reason, SKIP.MANUAL);
  assert.strictEqual(r.shouldLock, true);
});
test('respects an explicit lock', () => {
  const s = freshStore(); s.lock('w1');
  assert.strictEqual(decide(base(s)).reason, SKIP.LOCKED);
});
test('skips a reworded title', () => {
  const s = freshStore();
  s.setAuthored('workspace', 'w1', 'Fix auth middleware');
  s.markRenamed('w1', Date.now() - 120000);
  const r = decide(base(s, { current: 'Fix auth middleware', desired: 'Fix auth middlewares', intent: 'Fix auth middlewares' }));
  assert.strictEqual(r.reason, SKIP.SIMILAR);
});
test('renames on a genuinely new intent', () => {
  const s = freshStore();
  s.setAuthored('workspace', 'w1', 'Fix auth middleware');
  s.markRenamed('w1', Date.now() - 120000);
  assert.strictEqual(decide(base(s, { current: 'Fix auth middleware', desired: 'Postgres index tuning', intent: 'Postgres index tuning' })).rename, true);
});
test('rate limits back-to-back renames', () => {
  const s = freshStore();
  s.setAuthored('workspace', 'w1', 'Fix auth middleware');
  s.markRenamed('w1', Date.now());
  const r = decide(base(s, { current: 'Fix auth middleware', desired: 'Postgres index tuning', intent: 'Postgres index tuning' }));
  assert.strictEqual(r.reason, SKIP.RATE_LIMITED);
  assert.ok(r.retryInMs > 0);
});
test('stays quiet while the agent is blocked', () => {
  assert.strictEqual(decide(base(freshStore(), { agentStatus: 'blocked' })).reason, SKIP.BLOCKED);
});
test('ignores a junk title', () => {
  assert.strictEqual(decide(base(freshStore(), { intent: 'zsh', desired: 'zsh' })).reason, SKIP.JUNK);
});
test('no-ops when the name already matches', () => {
  assert.strictEqual(decide(base(freshStore(), { current: 'Fix auth middleware' })).reason, SKIP.UNCHANGED);
});

process.stdout.write('\nnamer\n');
const agent = (over = {}) => ({
  pane_id: 'w1:p1', tab_id: 'w1:t1', workspace_id: 'w1', agent: 'claude',
  agent_status: 'working', terminal_title_stripped: 'Fix auth middleware',
  cwd: '/Users/x/Code/app', foreground_cwd: '/Users/x/Code/app', ...over,
});
const snapshot = (agents, workspaces) => ({
  workspaces: workspaces || [{ workspace_id: 'w1', number: 1, label: 'app' }],
  tabs: [{ tab_id: 'w1:t1', label: 'app' }, { tab_id: 'w1:t2', label: 'app' }],
  panes: [], agents,
});

testAsync('plans a workspace and agent rename', async () => {
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([agent()]));
  const ws = plans.find((p) => p.kind === 'workspace');
  const ag = plans.find((p) => p.kind === 'agent');
  assert.strictEqual(ws.desired, 'Fix auth middleware');
  assert.strictEqual(ws.verdict.rename, true);
  assert.strictEqual(ag.desired, 'fix-auth-middleware');
});
testAsync('falls back to tabs when a workspace holds several agents', async () => {
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(),
    agent({ pane_id: 'w1:p2', tab_id: 'w1:t2', terminal_title_stripped: 'Postgres index tuning' }),
  ]));
  assert.strictEqual(plans.some((p) => p.kind === 'workspace'), false, 'workspace must stay untouched');
  assert.strictEqual(plans.filter((p) => p.kind === 'tab').length, 2);
});
testAsync('gives colliding agents distinct names', async () => {
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(),
    agent({ pane_id: 'w1:p2', tab_id: 'w1:t2' }),
  ]));
  const names = plans.filter((p) => p.kind === 'agent').map((p) => p.desired);
  assert.strictEqual(new Set(names).size, names.length, 'duplicate agent names: ' + names.join(','));
});
test('leadAgent refuses to guess between several agents', () => {
  assert.strictEqual(leadAgent([agent(), agent()], 'tab'), null);
  assert.ok(leadAgent([agent()], 'tab'));
});

process.stdout.write('\nproject + metadata\n');

test('repoNameFromUrl reads the repo name out of any remote form', () => {
  assert.strictEqual(repoNameFromUrl('git@github.com:oddurs/fontina.git'), 'fontina');
  assert.strictEqual(repoNameFromUrl('https://github.com/oddurs/bedreader.git'), 'bedreader');
  assert.strictEqual(repoNameFromUrl('ssh://git@host:22/team/repo.git'), 'repo');
  assert.strictEqual(repoNameFromUrl('/srv/git/thing.git'), 'thing');
  assert.strictEqual(repoNameFromUrl(''), '');
  assert.strictEqual(repoNameFromUrl(null), '');
});

test('manifestName prefers what a project calls itself', () => {
  // This repo declares "namesync" in package.json.
  assert.strictEqual(manifestName(path.join(__dirname, '..')), 'namesync');
  assert.strictEqual(manifestName('/tmp'), '');
});

testAsync('detectProject resolves a repo from a subdirectory', async () => {
  const here = await detectProject(__dirname);
  assert.ok(here && !here.includes('/'), 'got ' + here);
  assert.notStrictEqual(here, 'test', 'should name the repo, not the subdir');
});

testAsync('gitInfo caches per directory instead of respawning git', async () => {
  gitCache.clear();
  const t0 = Date.now();
  await gitInfo(__dirname, t0);
  const first = gitCache.size;
  await gitInfo(__dirname, t0 + 10);
  await gitInfo(__dirname, t0 + 20);
  assert.strictEqual(gitCache.size, first, 'repeat lookups must not add entries');
  // Past the TTL the entry is refreshed rather than served stale.
  const before = gitCache.get(__dirname).at;
  await gitInfo(__dirname, t0 + 60000);
  assert.notStrictEqual(gitCache.get(__dirname).at, before, 'TTL should refresh');
});

testAsync('publishMetadata sends project, branch and intent once each', async () => {
  const sent = [];
  const sink = {
    name: 'herdr',
    apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, id, tokens }); return true; },
  };
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [sink] });
  const snap = snapshot([agent()]);

  // One pane row and one workspace row: the two panels read different sources.
  assert.strictEqual(await n.publishMetadata(snap), 2);
  const pane = sent.find((x) => x.kind === 'pane');
  const ws = sent.find((x) => x.kind === 'workspace');
  assert.ok(pane, 'Agent rows need pane metadata');
  assert.strictEqual(pane.id, 'w1:p1');
  assert.ok('project' in pane.tokens && 'branch' in pane.tokens);
  assert.strictEqual(ws.id, 'w1');
  assert.strictEqual(ws.tokens.intent, 'Fix auth middleware');

  // Unchanged tokens must not be republished on every sync.
  assert.strictEqual(await n.publishMetadata(snap), 0);
  assert.strictEqual(sent.length, 2, 'republished identical metadata');
});

testAsync('publishMetadata reports an agent count only when ambiguous', async () => {
  const sent = [];
  const sink = { name: 'herdr', apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, tokens }); return true; } };
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata(snapshot([agent(), agent({ pane_id: 'w1:p2', tab_id: 'w1:t2' })]));
  const ws = sent.find((x) => x.kind === 'workspace');
  assert.strictEqual(ws.tokens.agents, '2');
});

testAsync('metadata is skipped when disabled', async () => {
  const sent = [];
  const sink = { name: 'herdr', apply: async () => true,
    reportMetadata: async () => { sent.push(1); return true; } };
  const c = cfg({ metadata: { enabled: false } });
  const n = new Namer({ cfg: c, store: freshStore(), sinks: [sink] });
  assert.strictEqual(await n.publishMetadata(snapshot([agent()])), 0);
  assert.strictEqual(sent.length, 0);
});

process.stdout.write('\nregressions\n');

testAsync('a lock-only pass is still written to disk', async () => {
  // save() used to run only when something was renamed, so backing off from a
  // hand-edited name was forgotten by the next process.
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [] });
  await n.apply([{ kind: 'workspace', id: 'w1', current: 'code quality',
    desired: 'Fix auth', verdict: { rename: false, shouldLock: true } }]);
  assert.ok(fs.existsSync(store.file), 'state file was never written');
  assert.ok(new Store(store.file).isLocked('w1'), 'lock did not survive a reload');
});

test('forget removes only the id it was given', () => {
  const s2 = freshStore();
  s2.lock('w1').setAuthored('workspace', 'w1', 'x').setAuthored('agent', 'w1:p1', 'y');
  s2.forget('w1:p1');
  assert.ok(s2.isLocked('w1'), 'closing a pane must not clear the workspace lock');
  assert.strictEqual(s2.authored('agent', 'w1:p1'), undefined);
});

testAsync('multiAgent "skip" still names the agents', async () => {
  const n = new Namer({ cfg: cfg({ multiAgent: 'skip' }), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(), agent({ pane_id: 'w1:p2', tab_id: 'w1:t2' }),
  ]));
  assert.ok(plans.some((p) => p.kind === 'agent'), 'skip must not disable agent naming');
  assert.ok(!plans.some((p) => p.kind === 'workspace'), 'skip must drop the workspace');
});

testAsync('a sink is never credited for a kind it cannot apply', async () => {
  const calls = [];
  const windowOnly = { name: 'window-only', kinds: ['workspace', 'tab'],
    apply: async ({ kind }) => { calls.push(kind); return true; } };
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [windowOnly] });
  await n.apply([{ kind: 'agent', id: 'w1:p1', current: '', desired: 'fix-auth',
    verdict: { rename: true } }]);
  assert.strictEqual(calls.length, 0, 'a window-only sink was asked to rename an agent');
  assert.strictEqual(store.authored('agent', 'w1:p1'), undefined,
    'authorship recorded for a rename that never happened');
});

testAsync('two agents sharing a tab yield one plan for it', async () => {
  const n = new Namer({ cfg: cfg({ targets: { workspace: false, tab: true, agent: false } }),
    store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(), agent({ pane_id: 'w1:p2', terminal_title_stripped: 'Postgres index tuning' }),
  ]));
  assert.strictEqual(plans.filter((p) => p.kind === 'tab' && p.id === 'w1:t1').length, 1,
    'duplicate plans for one tab');
});

test('a scalar in user config cannot replace an object default', () => {
  const merged = config.deepMerge(config.DEFAULTS, { targets: null, debounceMs: 10 });
  assert.strictEqual(typeof merged.targets, 'object');
  assert.strictEqual(merged.targets.agent, true);
  assert.strictEqual(merged.debounceMs, 10, 'scalars should still override');
});

test('ordinary words starting with a command verb are still intents', () => {
  const c = cfg();
  for (const t of ['go routine leak fix', 'make the build faster', 'node version bump',
    'less noisy logs', 'man page rewrite', 'code review agent', 'git blame tooling']) {
    assert.ok(!naming.isJunkTitle(t, c), 'should be intent: ' + t);
  }
  for (const t of ['cd namesync', 'git status', 'claude --dangerously-skip-permissions']) {
    assert.ok(naming.isJunkTitle(t, c), 'should be junk: ' + t);
  }
});

test('force skips the churn guards but not the safety ones', () => {
  const base = (store, over = {}) => ({
    kind: 'workspace', id: 'w1', cfg: cfg(), store, agentStatus: 'working',
    context: { repo: 'app', dirName: 'app' },
    current: 'Fix auth middleware', desired: 'Fix auth middlewares',
    intent: 'Fix auth middlewares', force: true, ...over,
  });
  const s1 = freshStore();
  s1.setAuthored('workspace', 'w1', 'Fix auth middleware').markRenamed('w1', Date.now());
  // Rate limit and similarity would both normally decline this.
  assert.strictEqual(decide(base(s1)).rename, true);

  // Safety rules still hold.
  const s2 = freshStore(); s2.lock('w1');
  assert.strictEqual(decide(base(s2)).reason, SKIP.LOCKED);
  const s3 = freshStore();
  assert.strictEqual(decide(base(s3, { current: 'hand written' })).reason, SKIP.MANUAL);
  const s4 = freshStore();
  assert.strictEqual(decide(base(s4, { agentStatus: 'blocked' })).reason, SKIP.BLOCKED);
  const s5 = freshStore();
  assert.strictEqual(decide(base(s5, { intent: 'zsh', desired: 'zsh' })).reason, SKIP.JUNK);
});

test('formatSince buckets coarsely so metadata rarely churns', () => {
  assert.strictEqual(naming.formatSince(0), 'now');
  assert.strictEqual(naming.formatSince(44000), 'now');
  assert.strictEqual(naming.formatSince(46000), '1m');
  assert.strictEqual(naming.formatSince(20 * 60000), '20m');
  assert.strictEqual(naming.formatSince(61 * 60000), '1h');
  assert.strictEqual(naming.formatSince(26 * 3600000), '1d');
  assert.strictEqual(naming.formatSince(NaN), 'now');
});

test('stateAt restarts the clock only when the state actually changes', () => {
  const st = freshStore();
  const t0 = 1000000;
  assert.deepStrictEqual(st.stateAt('w1:p1', 'working', t0), { at: t0, changed: true });
  // Same state later: the original timestamp is kept, so elapsed keeps growing.
  assert.deepStrictEqual(st.stateAt('w1:p1', 'working', t0 + 60000), { at: t0, changed: false });
  // A real transition resets it.
  assert.deepStrictEqual(st.stateAt('w1:p1', 'blocked', t0 + 90000),
    { at: t0 + 90000, changed: true });
});

test('forget clears everything inside a workspace, not just its own key', () => {
  const st = freshStore();
  st.lock('w1').lock('w1:p1');
  st.setAuthored('workspace', 'w1', 'a')
    .setAuthored('tab', 'w1:t1', 'b')
    .setAuthored('agent', 'w1:p1', 'c');
  st.setMetadata('workspace:w1', '{}').setMetadata('pane:w1:p1', '{}');
  st.markRenamed('w1'); st.markRenamed('w1:p1');
  st.stateAt('w1:p1', 'working', 1000);

  st.forget('w1');

  assert.strictEqual(st.isLocked('w1'), false);
  assert.strictEqual(st.isLocked('w1:p1'), false, 'agent lock left behind');
  assert.strictEqual(st.authored('agent', 'w1:p1'), undefined, 'agent authorship left behind');
  assert.strictEqual(st.authored('tab', 'w1:t1'), undefined, 'tab authorship left behind');
  assert.strictEqual(st.metadata('pane:w1:p1'), undefined, 'pane metadata left behind');
  assert.deepStrictEqual(Object.keys(st.data.lastRenameAt), []);
  assert.deepStrictEqual(Object.keys(st.data.stateAt), []);
});

test('an agent lock is releasable — it is keyed by pane id', () => {
  // unlock() forgets the workspace, which must reach locks keyed by pane id or
  // agent renaming wedges itself with no way back.
  const st = freshStore();
  st.lock('w1:p1', 'edited by hand');
  st.forget('w1');
  assert.strictEqual(st.isLocked('w1:p1'), false);
});

test('forgetting a sibling does not disturb a workspace', () => {
  const st = freshStore();
  st.lock('w1').lock('w10');
  st.forget('w1');
  assert.strictEqual(st.isLocked('w10'), true, 'w1 must not match w10');
});

test('a pane closing clears its duration clock', () => {
  const st = freshStore();
  st.stateAt('w1:p1', 'working', 1000);
  st.forget('w1:p1');
  assert.deepStrictEqual(st.stateAt('w1:p1', 'working', 5000), { at: 5000, changed: true });
});

testAsync('$since is published, and omitted when disabled', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, tokens }); return true; } };
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata(snapshot([agent()]));
  assert.strictEqual(sent.find((x) => x.kind === 'pane').tokens.since, 'now');

  const off = [];
  const sink2 = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { off.push(tokens); return true; } };
  const n2 = new Namer({ cfg: cfg({ showDuration: false }), store: freshStore(), sinks: [sink2] });
  await n2.publishMetadata(snapshot([agent()]));
  assert.strictEqual(off[0].since, null);
});

process.stdout.write('\ngrouping\n');

const ws = (id, project, over = {}) => ({
  workspace_id: id, label: id, tokens: project ? { project, ...over } : {},
});

test('a project is gathered where its earliest member already sits', () => {
  const { ordered } = planOrder([
    ws('w1', 'fontina'), ws('w2', 'cairn'), ws('w3', 'fontina'), ws('w4', 'ptop'),
  ]);
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w1', 'w3', 'w2', 'w4']);
});

test('grouping is idempotent', () => {
  const first = planOrder([
    ws('w1', 'fontina'), ws('w2', 'cairn'), ws('w3', 'fontina'),
  ]).ordered;
  const second = planOrder(first);
  assert.strictEqual(second.changed, false, 'a second pass should be a no-op');
  assert.deepStrictEqual(second.ordered.map((w) => w.workspace_id),
    first.map((w) => w.workspace_id));
});

test('worktrees follow their project\'s main checkout', () => {
  const { ordered } = planOrder([
    ws('w1', 'fontina', { worktree: 'worktree' }),
    ws('w2', 'fontina'),
    ws('w3', 'cairn'),
  ]);
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w2', 'w1', 'w3']);
});

test('spaces with no project keep their place', () => {
  const { ordered, changed } = planOrder([ws('w1'), ws('w2'), ws('w3')]);
  assert.strictEqual(changed, false, 'nothing to group, nothing should move');
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w1', 'w2', 'w3']);
});

test('movement is minimal — settled spaces are left alone', () => {
  // Only w4 is out of place; w1..w3 must not be disturbed.
  const { moved } = planOrder([
    ws('w1', 'fontina'), ws('w2', 'fontina'), ws('w3', 'cairn'), ws('w4', 'fontina'),
  ]);
  assert.deepStrictEqual(moved.map((m) => m.workspace_id).sort(), ['w3', 'w4']);
});

test('a claimed workspace holds its position while others regroup', () => {
  // A dashboard is furniture. Sorting it around by whatever project it happens
  // to report would be worse than leaving the spaces ungrouped.
  const { ordered, moved } = planOrder([
    ws('w1', 'fontina'),
    { workspace_id: 'wG', label: 'OddOS', tokens: { role: 'dashboard', project: 'OddOS' } },
    ws('w3', 'cairn'),
    ws('w4', 'fontina'),
  ]);
  assert.strictEqual(ordered[1].workspace_id, 'wG', 'the claimed space moved');
  assert.strictEqual(moved.some((m) => m.workspace_id === 'wG'), false);
  // and the rest still group around it
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w1', 'wG', 'w4', 'w3']);
});

test('pinning stays idempotent', () => {
  const input = [
    ws('w1', 'fontina'),
    { workspace_id: 'wG', label: 'OddOS', tokens: { role: 'dashboard' } },
    ws('w3', 'cairn'),
    ws('w4', 'fontina'),
  ];
  const once = planOrder(input).ordered;
  const twice = planOrder(once);
  assert.strictEqual(twice.changed, false);
  assert.deepStrictEqual(twice.ordered.map((w) => w.workspace_id),
    once.map((w) => w.workspace_id));
});

test('moved reports the jump keys that change', () => {
  const { moved } = planOrder([ws('w1', 'a'), ws('w2', 'b'), ws('w3', 'a')]);
  const m = moved.find((x) => x.workspace_id === 'w3');
  assert.strictEqual(m.from, 3);
  assert.strictEqual(m.to, 2);
});

process.stdout.write('\nproject reliability\n');

function tmpProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ns-'));
  for (const [name, body] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, name), body);
  }
  return dir;
}

test('a go module major-version suffix is not the project name', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'go.mod': 'module github.com/oddurs/widgets/v2\n' })),
    'widgets');
  assert.strictEqual(
    manifestName(tmpProject({ 'go.mod': 'module github.com/oddurs/widgets\n' })),
    'widgets');
});

test('an npm scope is stripped', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'package.json': '{"name":"@acme/widget"}' })), 'widget');
});

test('Cargo and pyproject names are read', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'Cargo.toml': '[package]\nname = "smali"\nversion = "0.1.0"\n' })),
    'smali');
  assert.strictEqual(
    manifestName(tmpProject({ 'pyproject.toml': '[project]\nname = "hoover"\n' })), 'hoover');
});

test('a Cargo workspace root with no [package] does not invent a name', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'Cargo.toml': '[workspace]\nmembers = ["a", "b"]\n' })), '');
});

test('directories that identify nothing are rejected', () => {
  assert.strictEqual(isUselessCwd('/'), true, 'panes report / while a command starts');
  assert.strictEqual(isUselessCwd(''), true);
  assert.strictEqual(isUselessCwd(process.env.HOME), true);
  assert.strictEqual(isUselessCwd('/Users/oddurs/Code/smali'), false);
});

test('a known project is not downgraded by a transient directory', () => {
  const st = freshStore();
  st.setLastProject('w1:p1', 'fontina');
  assert.strictEqual(st.lastProject('w1:p1'), 'fontina');
  // and it is cleared with the rest of the pane's state
  st.forget('w1:p1');
  assert.strictEqual(st.lastProject('w1:p1'), undefined);
});

process.stdout.write('\ninterop\n');

test('isClaimed recognises another plugin\'s marker', () => {
  assert.strictEqual(isClaimed({ tokens: { role: 'dashboard' } }), true);
  assert.strictEqual(isClaimed({ tokens: { project: 'fontina' } }), false);
  assert.strictEqual(isClaimed({ tokens: {} }), false);
  assert.strictEqual(isClaimed({}), false);
  assert.strictEqual(isClaimed(undefined), false);
});

testAsync('a claimed workspace is never renamed', async () => {
  // herdr's tokens are one flat map, so naming this would overwrite the
  // claiming plugin's own project/n and erase its sidebar row.
  const claimed = [{ workspace_id: 'w1', number: 1, label: 'OddOS',
    tokens: { role: 'dashboard', project: 'OddOS', n: '\u25c6' } }];
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans({ ...snapshot([agent()]), workspaces: claimed });
  assert.strictEqual(plans.length, 0, 'claimed workspace must be left alone');
});

testAsync('a claimed workspace gets no metadata written over it', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, id, tokens }); return true; } };
  const claimed = [{ workspace_id: 'w1', number: 1, label: 'OddOS',
    tokens: { role: 'dashboard', project: 'OddOS' } }];
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata({ ...snapshot([agent()]), workspaces: claimed });
  assert.strictEqual(sent.length, 0, 'would have overwritten the claiming plugin');
});

testAsync('the guard can be turned off', async () => {
  const claimed = [{ workspace_id: 'w1', number: 1, label: 'OddOS',
    tokens: { role: 'dashboard' } }];
  const n = new Namer({ cfg: cfg({ respectPluginRoles: false }), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans({ ...snapshot([agent()]), workspaces: claimed });
  assert.ok(plans.length > 0, 'opting out should restore normal behaviour');
});

Promise.all(pending).then(() => {
  process.stdout.write('\n' + passed + ' passed, ' + failed + ' failed\n');
  process.exit(failed ? 1 : 0);
});
