'use strict';
const assert = require('assert');
const os = require('os');
const path = require('path');
const fs = require('fs');

const naming = require('../src/naming');
const { decide, SKIP } = require('../src/policy');
const { Store } = require('../src/state');
const { Namer, leadAgent, gitInfo, gitCache, detectProject,
  repoNameFromUrl, manifestName } = require('../src/namer');
const { planOrder, isClaimed } = require('../src/grouping');
const { isUselessCwd } = require('../src/namer');
const setup = require('../src/setup');
const viewport = require('../src/viewport');
const { createLlmSource, usable } = require('../src/sources/llm');
const http = require('http');
const transcript = require('../src/transcript');
const { resolveSources, observe, createTitleSource } = require('../src/sources');
const config = require('../src/config');

let passed = 0;
let failed = 0;
// Async tests were fired off unawaited and reported from a fixed timer, so a
// slow one could be cut off while the run still printed "0 failed".
const pending = [];
function test(name, fn) {
  try { fn(); passed += 1; process.stdout.write('  ok   ' + name + '\n'); }
  catch (err) { failed += 1; process.stdout.write('  FAIL ' + name + '\n       ' + err.message + '\n'); }
}
function testAsync(name, fn) {
  pending.push(Promise.resolve().then(fn).then(
    () => { passed += 1; process.stdout.write('  ok   ' + name + '\n'); },
    (err) => { failed += 1; process.stdout.write('  FAIL ' + name + '\n       ' + err.message + '\n'); },
  ));
}

function freshStore() {
  const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'mn-')), 'state.json');
  return new Store(file);
}
// Never config.load(): that reads the developer's installed config, so a tuned
// similarityThreshold would fail these tests for reasons unrelated to a change.
const cfg = (over = {}) => config.deepMerge(config.DEFAULTS, over);

process.stdout.write('\nnaming\n');
test('slugify fits herdr agent-name rules', () => {
  const s = naming.slugify('Herdr session naming plugin');
  assert.match(s, /^[a-z][a-z0-9_-]{0,31}$/);
  assert.strictEqual(s, 'herdr-session-naming-plugin');
});
test('slugify prefixes a leading digit', () => {
  assert.match(naming.slugify('3 failing tests'), /^[a-z]/);
});
test('slugify truncates on a word boundary', () => {
  const s = naming.slugify('Refactor the authentication middleware and session layer');
  assert.ok(s.length <= 32, 'length ' + s.length);
  assert.ok(!s.endsWith('-'));
});
test('normalize strips the agent state glyph', () => {
  assert.strictEqual(naming.normalize('◐ Herdr session naming plugin'), 'Herdr session naming plugin');
  assert.strictEqual(naming.normalize('✳ Astro docs site'), 'Astro docs site');
});
test('similarity treats rewordings as the same intent', () => {
  assert.ok(naming.similarity('rename tmux window', 'renaming tmux windows') >= 0.9);
  assert.ok(naming.similarity('Herdr naming plugin', 'Herdr naming plugins') >= 0.9);
});
test('similarity separates unrelated intents', () => {
  assert.ok(naming.similarity('Herdr naming plugin', 'Postgres index tuning') < 0.2);
});
test('looksAutoGenerated recognises herdr defaults', () => {
  assert.ok(naming.looksAutoGenerated('unifont', { repo: 'unifont' }));
  assert.ok(naming.looksAutoGenerated('w3'));
  assert.ok(naming.looksAutoGenerated('tab 2'));
  assert.ok(naming.looksAutoGenerated(''));
  assert.ok(!naming.looksAutoGenerated('code quality', { repo: 'unifont' }));
});

test('a name that only restates the location is nobody\'s choice', () => {
  // herdr labels a workspace from its directory, and its rename dialog puts a
  // directory name back when a name is cleared. Holding the workspace on the
  // strength of that would freeze it on the one name the user was removing.
  const ctx = {
    project: 'fontina',
    repo: 'feat-collection-relative-paths',
    paneDir: 'unifont',
    foregroundDir: 'feat-collection-relative-paths',
    branch: 'feat/packaging-manifests',
  };
  for (const label of ['unifont', 'fontina', 'feat-collection-relative-paths',
    'feat/packaging-manifests']) {
    assert.ok(naming.looksAutoGenerated(label, ctx), 'should be adoptable: ' + label);
  }
  // A name someone actually chose still stands.
  for (const label of ['m5', 'code quality', 'Richard Stallman perspective']) {
    assert.ok(!naming.looksAutoGenerated(label, ctx), 'should be held: ' + label);
  }
});
test('uniqueAgentName avoids collisions and stays in range', () => {
  const n = naming.uniqueAgentName('fix-auth', new Set(['fix-auth']));
  assert.strictEqual(n, 'fix-auth-2');
  const long = naming.uniqueAgentName('a'.repeat(32), new Set(['a'.repeat(32)]));
  assert.ok(long.length <= 32);
});
test('isJunkTitle rejects paths, shells and the bare repo name', () => {
  const c = cfg();
  assert.ok(naming.isJunkTitle('~/Code/foo', c));
  assert.ok(naming.isJunkTitle('zsh', c));
  assert.ok(naming.isJunkTitle('unifont', c, { repo: 'unifont' }));
  assert.ok(!naming.isJunkTitle('Fix auth middleware', c));
});
test('isJunkTitle rejects shell prompts and typed commands', () => {
  const c = cfg();
  // All observed live in the herdr pane.updated stream before an agent starts.
  for (const t of ['oddurs@host:~/Code/perfect', 'cd namesync',
    'claude --dangerously-skip-permissions', 'Claude Code', 'git status']) {
    assert.ok(naming.isJunkTitle(t, c), 'should be junk: ' + t);
  }
});
test('isJunkTitle keeps real intents, including tool-named ones', () => {
  const c = cfg();
  for (const t of ['Herdr session naming plugin', 'Open source wifi e-reader',
    'ptop-adopt-remaining-lessons', 'Linux system monitor tool',
    'Fix parser - a big job', 'Apple Notes-style Obsidian app']) {
    assert.ok(!naming.isJunkTitle(t, c), 'should be intent: ' + t);
  }
});
test('stripping nothing leaves the case alone', () => {
  // Capitalising unconditionally would rewrite the first letter of every
  // lowercase title, whether or not a prefix was removed.
  assert.strictEqual(naming.stripProject('fix the parser', 'app'), 'fix the parser');
  assert.strictEqual(naming.stripProject('app fix the parser', 'app'), 'Fix the parser');
});

test('render fills template tokens', () => {
  assert.strictEqual(naming.render('{repo} - {intent}', { repo: 'app', intent: 'Fix auth' }), 'app - Fix auth');
});

process.stdout.write('\npolicy\n');
const base = (store, over = {}) => ({
  kind: 'workspace', id: 'w1', cfg: cfg(), store,
  agentStatus: 'working', context: { repo: 'unifont', dirName: 'unifont' },
  current: 'unifont', desired: 'Fix auth middleware', intent: 'Fix auth middleware',
  ...over,
});

test('adopts a workspace still using herdr default label', () => {
  assert.strictEqual(decide(base(freshStore())).rename, true);
});
test('never overwrites a hand-written name, and locks it', () => {
  const r = decide(base(freshStore(), { current: 'code quality' }));
  assert.strictEqual(r.rename, false);
  assert.strictEqual(r.reason, SKIP.MANUAL);
  assert.strictEqual(r.shouldLock, true);
});
test('respects an explicit lock', () => {
  const s = freshStore(); s.lock('w1');
  assert.strictEqual(decide(base(s)).reason, SKIP.LOCKED);
});
test('skips a reworded title', () => {
  const s = freshStore();
  s.setAuthored('workspace', 'w1', 'Fix auth middleware');
  s.markRenamed('w1', Date.now() - 120000);
  const r = decide(base(s, { current: 'Fix auth middleware', desired: 'Fix auth middlewares', intent: 'Fix auth middlewares' }));
  assert.strictEqual(r.reason, SKIP.SIMILAR);
});
test('renames on a genuinely new intent', () => {
  const s = freshStore();
  s.setAuthored('workspace', 'w1', 'Fix auth middleware');
  s.markRenamed('w1', Date.now() - 120000);
  assert.strictEqual(decide(base(s, { current: 'Fix auth middleware', desired: 'Postgres index tuning', intent: 'Postgres index tuning' })).rename, true);
});
test('rate limits back-to-back renames', () => {
  const s = freshStore();
  s.setAuthored('workspace', 'w1', 'Fix auth middleware');
  s.markRenamed('w1', Date.now());
  const r = decide(base(s, { current: 'Fix auth middleware', desired: 'Postgres index tuning', intent: 'Postgres index tuning' }));
  assert.strictEqual(r.reason, SKIP.RATE_LIMITED);
  assert.ok(r.retryInMs > 0);
});
test('stays quiet while the agent is blocked', () => {
  assert.strictEqual(decide(base(freshStore(), { agentStatus: 'blocked' })).reason, SKIP.BLOCKED);
});
test('ignores a junk title', () => {
  assert.strictEqual(decide(base(freshStore(), { intent: 'zsh', desired: 'zsh' })).reason, SKIP.JUNK);
});
test('no-ops when the name already matches', () => {
  assert.strictEqual(decide(base(freshStore(), { current: 'Fix auth middleware' })).reason, SKIP.UNCHANGED);
});

process.stdout.write('\nnamer\n');
const agent = (over = {}) => ({
  pane_id: 'w1:p1', tab_id: 'w1:t1', workspace_id: 'w1', agent: 'claude',
  agent_status: 'working', terminal_title_stripped: 'Fix auth middleware',
  cwd: '/Users/x/Code/app', foreground_cwd: '/Users/x/Code/app', ...over,
});
const snapshot = (agents, workspaces) => ({
  workspaces: workspaces || [{ workspace_id: 'w1', number: 1, label: 'app' }],
  tabs: [{ tab_id: 'w1:t1', label: 'app' }, { tab_id: 'w1:t2', label: 'app' }],
  panes: [], agents,
});

testAsync('plans a workspace and agent rename', async () => {
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([agent()]));
  const ws = plans.find((p) => p.kind === 'workspace');
  const ag = plans.find((p) => p.kind === 'agent');
  assert.strictEqual(ws.desired, 'Fix auth middleware');
  assert.strictEqual(ws.verdict.rename, true);
  assert.strictEqual(ag.desired, 'fix-auth-middleware');
});
testAsync('falls back to tabs when a workspace holds several agents', async () => {
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(),
    agent({ pane_id: 'w1:p2', tab_id: 'w1:t2', terminal_title_stripped: 'Postgres index tuning' }),
  ]));
  assert.strictEqual(plans.some((p) => p.kind === 'workspace'), false, 'workspace must stay untouched');
  assert.strictEqual(plans.filter((p) => p.kind === 'tab').length, 2);
});
testAsync('gives colliding agents distinct names', async () => {
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(),
    agent({ pane_id: 'w1:p2', tab_id: 'w1:t2' }),
  ]));
  const names = plans.filter((p) => p.kind === 'agent').map((p) => p.desired);
  assert.strictEqual(new Set(names).size, names.length, 'duplicate agent names: ' + names.join(','));
});
test('leadAgent refuses to guess between several agents', () => {
  assert.strictEqual(leadAgent([agent(), agent()], 'tab'), null);
  assert.ok(leadAgent([agent()], 'tab'));
});

process.stdout.write('\nproject + metadata\n');

test('repoNameFromUrl reads the repo name out of any remote form', () => {
  assert.strictEqual(repoNameFromUrl('git@github.com:oddurs/fontina.git'), 'fontina');
  assert.strictEqual(repoNameFromUrl('https://github.com/oddurs/bedreader.git'), 'bedreader');
  assert.strictEqual(repoNameFromUrl('ssh://git@host:22/team/repo.git'), 'repo');
  assert.strictEqual(repoNameFromUrl('/srv/git/thing.git'), 'thing');
  assert.strictEqual(repoNameFromUrl(''), '');
  assert.strictEqual(repoNameFromUrl(null), '');
});

test('manifestName prefers what a project calls itself', () => {
  // This repo declares "namesync" in package.json.
  assert.strictEqual(manifestName(path.join(__dirname, '..')), 'namesync');
  assert.strictEqual(manifestName('/tmp'), '');
});

testAsync('detectProject resolves a repo from a subdirectory', async () => {
  const here = await detectProject(__dirname);
  assert.ok(here && !here.includes('/'), 'got ' + here);
  assert.notStrictEqual(here, 'test', 'should name the repo, not the subdir');
});

testAsync('gitInfo caches per directory instead of respawning git', async () => {
  gitCache.clear();
  const t0 = Date.now();
  await gitInfo(__dirname, t0);
  const first = gitCache.size;
  await gitInfo(__dirname, t0 + 10);
  await gitInfo(__dirname, t0 + 20);
  assert.strictEqual(gitCache.size, first, 'repeat lookups must not add entries');
  // Past the TTL the entry is refreshed rather than served stale.
  const before = gitCache.get(__dirname).at;
  await gitInfo(__dirname, t0 + 60000);
  assert.notStrictEqual(gitCache.get(__dirname).at, before, 'TTL should refresh');
});

testAsync('publishMetadata sends project, branch and intent once each', async () => {
  const sent = [];
  const sink = {
    name: 'herdr',
    apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, id, tokens }); return true; },
  };
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [sink] });
  const snap = snapshot([agent()]);

  // One pane row and one workspace row: the two panels read different sources.
  assert.strictEqual(await n.publishMetadata(snap), 2);
  const pane = sent.find((x) => x.kind === 'pane');
  const ws = sent.find((x) => x.kind === 'workspace');
  assert.ok(pane, 'Agent rows need pane metadata');
  assert.strictEqual(pane.id, 'w1:p1');
  assert.ok('project' in pane.tokens && 'branch' in pane.tokens);
  assert.strictEqual(ws.id, 'w1');
  assert.strictEqual(ws.tokens.intent, 'Fix auth middleware');

  // Unchanged tokens must not be republished on every sync.
  assert.strictEqual(await n.publishMetadata(snap), 0);
  assert.strictEqual(sent.length, 2, 'republished identical metadata');
});

testAsync('publishMetadata reports an agent count only when ambiguous', async () => {
  const sent = [];
  const sink = { name: 'herdr', apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, tokens }); return true; } };
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata(snapshot([agent(), agent({ pane_id: 'w1:p2', tab_id: 'w1:t2' })]));
  const ws = sent.find((x) => x.kind === 'workspace');
  assert.strictEqual(ws.tokens.agents, '2');
});

testAsync('metadata is skipped when disabled', async () => {
  const sent = [];
  const sink = { name: 'herdr', apply: async () => true,
    reportMetadata: async () => { sent.push(1); return true; } };
  const c = cfg({ metadata: { enabled: false } });
  const n = new Namer({ cfg: c, store: freshStore(), sinks: [sink] });
  assert.strictEqual(await n.publishMetadata(snapshot([agent()])), 0);
  assert.strictEqual(sent.length, 0);
});

process.stdout.write('\nregressions\n');

testAsync('a lock-only pass is still written to disk', async () => {
  // save() used to run only when something was renamed, so backing off from a
  // hand-edited name was forgotten by the next process.
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [] });
  await n.apply([{ kind: 'workspace', id: 'w1', current: 'code quality',
    desired: 'Fix auth', verdict: { rename: false, shouldLock: true } }]);
  assert.ok(fs.existsSync(store.file), 'state file was never written');
  assert.ok(new Store(store.file).isLocked('w1'), 'lock did not survive a reload');
});

test('forget removes only the id it was given', () => {
  const s2 = freshStore();
  s2.lock('w1').setAuthored('workspace', 'w1', 'x').setAuthored('agent', 'w1:p1', 'y');
  s2.forget('w1:p1');
  assert.ok(s2.isLocked('w1'), 'closing a pane must not clear the workspace lock');
  assert.strictEqual(s2.authored('agent', 'w1:p1'), undefined);
});

testAsync('multiAgent "skip" still names the agents', async () => {
  const n = new Namer({ cfg: cfg({ multiAgent: 'skip' }), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(), agent({ pane_id: 'w1:p2', tab_id: 'w1:t2' }),
  ]));
  assert.ok(plans.some((p) => p.kind === 'agent'), 'skip must not disable agent naming');
  assert.ok(!plans.some((p) => p.kind === 'workspace'), 'skip must drop the workspace');
});

testAsync('a sink is never credited for a kind it cannot apply', async () => {
  const calls = [];
  const windowOnly = { name: 'window-only', kinds: ['workspace', 'tab'],
    apply: async ({ kind }) => { calls.push(kind); return true; } };
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [windowOnly] });
  await n.apply([{ kind: 'agent', id: 'w1:p1', current: '', desired: 'fix-auth',
    verdict: { rename: true } }]);
  assert.strictEqual(calls.length, 0, 'a window-only sink was asked to rename an agent');
  assert.strictEqual(store.authored('agent', 'w1:p1'), undefined,
    'authorship recorded for a rename that never happened');
});

testAsync('two agents sharing a tab yield one plan for it', async () => {
  const n = new Namer({ cfg: cfg({ targets: { workspace: false, tab: true, agent: false } }),
    store: freshStore(), sinks: [] });
  const plans = await n.buildPlans(snapshot([
    agent(), agent({ pane_id: 'w1:p2', terminal_title_stripped: 'Postgres index tuning' }),
  ]));
  assert.strictEqual(plans.filter((p) => p.kind === 'tab' && p.id === 'w1:t1').length, 1,
    'duplicate plans for one tab');
});

test('a scalar in user config cannot replace an object default', () => {
  const merged = config.deepMerge(config.DEFAULTS, { targets: null, debounceMs: 10 });
  assert.strictEqual(typeof merged.targets, 'object');
  assert.strictEqual(merged.targets.agent, true);
  assert.strictEqual(merged.debounceMs, 10, 'scalars should still override');
});

test('ordinary words starting with a command verb are still intents', () => {
  const c = cfg();
  for (const t of ['go routine leak fix', 'make the build faster', 'node version bump',
    'less noisy logs', 'man page rewrite', 'code review agent', 'git blame tooling']) {
    assert.ok(!naming.isJunkTitle(t, c), 'should be intent: ' + t);
  }
  for (const t of ['cd namesync', 'git status', 'claude --dangerously-skip-permissions']) {
    assert.ok(naming.isJunkTitle(t, c), 'should be junk: ' + t);
  }
});

test('force skips the churn guards but not the safety ones', () => {
  const base = (store, over = {}) => ({
    kind: 'workspace', id: 'w1', cfg: cfg(), store, agentStatus: 'working',
    context: { repo: 'app', dirName: 'app' },
    current: 'Fix auth middleware', desired: 'Fix auth middlewares',
    intent: 'Fix auth middlewares', force: true, ...over,
  });
  const s1 = freshStore();
  s1.setAuthored('workspace', 'w1', 'Fix auth middleware').markRenamed('w1', Date.now());
  // Rate limit and similarity would both normally decline this.
  assert.strictEqual(decide(base(s1)).rename, true);

  // Safety rules still hold.
  const s2 = freshStore(); s2.lock('w1');
  assert.strictEqual(decide(base(s2)).reason, SKIP.LOCKED);
  const s3 = freshStore();
  assert.strictEqual(decide(base(s3, { current: 'hand written' })).reason, SKIP.MANUAL);
  const s4 = freshStore();
  assert.strictEqual(decide(base(s4, { agentStatus: 'blocked' })).reason, SKIP.BLOCKED);
  const s5 = freshStore();
  assert.strictEqual(decide(base(s5, { intent: 'zsh', desired: 'zsh' })).reason, SKIP.JUNK);
});

test('formatSince buckets coarsely so metadata rarely churns', () => {
  assert.strictEqual(naming.formatSince(0), 'now');
  assert.strictEqual(naming.formatSince(44000), 'now');
  assert.strictEqual(naming.formatSince(46000), '1m');
  assert.strictEqual(naming.formatSince(9 * 60000), '9m', 'minutes matter early');
  assert.strictEqual(naming.formatSince(61 * 60000), '1h');
  assert.strictEqual(naming.formatSince(26 * 3600000), '1d');
  assert.strictEqual(naming.formatSince(NaN), 'now');
});

test('past ten minutes the value steps, so it stops rewriting every minute', () => {
  // Each change is a metadata write and a redraw for every agent.
  assert.strictEqual(naming.formatSince(12 * 60000), '10m');
  assert.strictEqual(naming.formatSince(14 * 60000), '10m');
  assert.strictEqual(naming.formatSince(15 * 60000), '15m');
  assert.strictEqual(naming.formatSince(59 * 60000), '55m');
  // An hour of minute-ticks would be 60 writes per agent; this is 10.
  const steps = new Set();
  for (let m = 10; m < 60; m += 1) steps.add(naming.formatSince(m * 60000));
  assert.ok(steps.size <= 10, 'too many distinct values in the first hour: ' + steps.size);
});

test('stateAt restarts the clock only when the state actually changes', () => {
  const st = freshStore();
  const t0 = 1000000;
  assert.deepStrictEqual(st.stateAt('w1:p1', 'working', t0), { at: t0, changed: true });
  // Same state later: the original timestamp is kept, so elapsed keeps growing.
  assert.deepStrictEqual(st.stateAt('w1:p1', 'working', t0 + 60000), { at: t0, changed: false });
  // A real transition resets it.
  assert.deepStrictEqual(st.stateAt('w1:p1', 'blocked', t0 + 90000),
    { at: t0 + 90000, changed: true });
});

test('forget clears everything inside a workspace, not just its own key', () => {
  const st = freshStore();
  st.lock('w1').lock('w1:p1');
  st.setAuthored('workspace', 'w1', 'a')
    .setAuthored('tab', 'w1:t1', 'b')
    .setAuthored('agent', 'w1:p1', 'c');
  st.setMetadata('workspace:w1', '{}').setMetadata('pane:w1:p1', '{}');
  st.markRenamed('w1'); st.markRenamed('w1:p1');
  st.stateAt('w1:p1', 'working', 1000);

  st.forget('w1');

  assert.strictEqual(st.isLocked('w1'), false);
  assert.strictEqual(st.isLocked('w1:p1'), false, 'agent lock left behind');
  assert.strictEqual(st.authored('agent', 'w1:p1'), undefined, 'agent authorship left behind');
  assert.strictEqual(st.authored('tab', 'w1:t1'), undefined, 'tab authorship left behind');
  assert.strictEqual(st.metadata('pane:w1:p1'), undefined, 'pane metadata left behind');
  assert.deepStrictEqual(Object.keys(st.data.lastRenameAt), []);
  assert.deepStrictEqual(Object.keys(st.data.stateAt), []);
});

test('an agent lock is releasable — it is keyed by pane id', () => {
  // unlock() forgets the workspace, which must reach locks keyed by pane id or
  // agent renaming wedges itself with no way back.
  const st = freshStore();
  st.lock('w1:p1', 'edited by hand');
  st.forget('w1');
  assert.strictEqual(st.isLocked('w1:p1'), false);
});

test('forgetting a sibling does not disturb a workspace', () => {
  const st = freshStore();
  st.lock('w1').lock('w10');
  st.forget('w1');
  assert.strictEqual(st.isLocked('w10'), true, 'w1 must not match w10');
});

test('a pane closing clears its duration clock', () => {
  const st = freshStore();
  st.stateAt('w1:p1', 'working', 1000);
  st.forget('w1:p1');
  assert.deepStrictEqual(st.stateAt('w1:p1', 'working', 5000), { at: 5000, changed: true });
});

testAsync('$since is published, and omitted when disabled', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, tokens }); return true; } };
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata(snapshot([agent()]));
  assert.strictEqual(sent.find((x) => x.kind === 'pane').tokens.since, 'now');

  const off = [];
  const sink2 = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { off.push(tokens); return true; } };
  const n2 = new Namer({ cfg: cfg({ showDuration: false }), store: freshStore(), sinks: [sink2] });
  await n2.publishMetadata(snapshot([agent()]));
  assert.strictEqual(off[0].since, null);
});

process.stdout.write('\ngrouping\n');

const ws = (id, project, over = {}) => ({
  workspace_id: id, label: id, tokens: project ? { project, ...over } : {},
});

test('a project is gathered where its earliest member already sits', () => {
  const { ordered } = planOrder([
    ws('w1', 'fontina'), ws('w2', 'cairn'), ws('w3', 'fontina'), ws('w4', 'ptop'),
  ]);
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w1', 'w3', 'w2', 'w4']);
});

test('grouping is idempotent', () => {
  const first = planOrder([
    ws('w1', 'fontina'), ws('w2', 'cairn'), ws('w3', 'fontina'),
  ]).ordered;
  const second = planOrder(first);
  assert.strictEqual(second.changed, false, 'a second pass should be a no-op');
  assert.deepStrictEqual(second.ordered.map((w) => w.workspace_id),
    first.map((w) => w.workspace_id));
});

test('worktrees follow their project\'s main checkout', () => {
  const { ordered } = planOrder([
    ws('w1', 'fontina', { worktree: 'worktree' }),
    ws('w2', 'fontina'),
    ws('w3', 'cairn'),
  ]);
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w2', 'w1', 'w3']);
});

test('spaces with no project keep their place', () => {
  const { ordered, changed } = planOrder([ws('w1'), ws('w2'), ws('w3')]);
  assert.strictEqual(changed, false, 'nothing to group, nothing should move');
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w1', 'w2', 'w3']);
});

test('movement is minimal — settled spaces are left alone', () => {
  // Only w4 is out of place; w1..w3 must not be disturbed.
  const { moved } = planOrder([
    ws('w1', 'fontina'), ws('w2', 'fontina'), ws('w3', 'cairn'), ws('w4', 'fontina'),
  ]);
  assert.deepStrictEqual(moved.map((m) => m.workspace_id).sort(), ['w3', 'w4']);
});

test('a claimed workspace holds its position while others regroup', () => {
  // A dashboard is furniture. Sorting it around by whatever project it happens
  // to report would be worse than leaving the spaces ungrouped.
  const { ordered, moved } = planOrder([
    ws('w1', 'fontina'),
    { workspace_id: 'wG', label: 'OddOS', tokens: { role: 'dashboard', project: 'OddOS' } },
    ws('w3', 'cairn'),
    ws('w4', 'fontina'),
  ]);
  assert.strictEqual(ordered[1].workspace_id, 'wG', 'the claimed space moved');
  assert.strictEqual(moved.some((m) => m.workspace_id === 'wG'), false);
  // and the rest still group around it
  assert.deepStrictEqual(ordered.map((w) => w.workspace_id), ['w1', 'wG', 'w4', 'w3']);
});

test('pinning stays idempotent', () => {
  const input = [
    ws('w1', 'fontina'),
    { workspace_id: 'wG', label: 'OddOS', tokens: { role: 'dashboard' } },
    ws('w3', 'cairn'),
    ws('w4', 'fontina'),
  ];
  const once = planOrder(input).ordered;
  const twice = planOrder(once);
  assert.strictEqual(twice.changed, false);
  assert.deepStrictEqual(twice.ordered.map((w) => w.workspace_id),
    once.map((w) => w.workspace_id));
});

test('moved reports the jump keys that change', () => {
  const { moved } = planOrder([ws('w1', 'a'), ws('w2', 'b'), ws('w3', 'a')]);
  const m = moved.find((x) => x.workspace_id === 'w3');
  assert.strictEqual(m.from, 3);
  assert.strictEqual(m.to, 2);
});

process.stdout.write('\nproject reliability\n');

function tmpProject(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ns-'));
  for (const [name, body] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, name), body);
  }
  return dir;
}

test('a go module major-version suffix is not the project name', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'go.mod': 'module github.com/oddurs/widgets/v2\n' })),
    'widgets');
  assert.strictEqual(
    manifestName(tmpProject({ 'go.mod': 'module github.com/oddurs/widgets\n' })),
    'widgets');
});

test('an npm scope is stripped', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'package.json': '{"name":"@acme/widget"}' })), 'widget');
});

test('Cargo and pyproject names are read', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'Cargo.toml': '[package]\nname = "ferris"\nversion = "0.1.0"\n' })),
    'ferris');
  assert.strictEqual(
    manifestName(tmpProject({ 'pyproject.toml': '[project]\nname = "hoover"\n' })), 'hoover');
});

test('a Cargo workspace root with no [package] does not invent a name', () => {
  assert.strictEqual(
    manifestName(tmpProject({ 'Cargo.toml': '[workspace]\nmembers = ["a", "b"]\n' })), '');
});

test('directories that identify nothing are rejected', () => {
  assert.strictEqual(isUselessCwd('/'), true, 'panes report / while a command starts');
  assert.strictEqual(isUselessCwd(''), true);
  assert.strictEqual(isUselessCwd(process.env.HOME), true);
  assert.strictEqual(isUselessCwd(path.join(os.tmpdir(), 'a-project')), false);
});

test('a known project is not downgraded by a transient directory', () => {
  const st = freshStore();
  st.setLastProject('w1:p1', 'fontina');
  assert.strictEqual(st.lastProject('w1:p1'), 'fontina');
  // and it is cleared with the rest of the pane's state
  st.forget('w1:p1');
  assert.strictEqual(st.lastProject('w1:p1'), undefined);
});

process.stdout.write('\ninterop\n');

test('isClaimed recognises another plugin\'s marker', () => {
  assert.strictEqual(isClaimed({ tokens: { role: 'dashboard' } }), true);
  assert.strictEqual(isClaimed({ tokens: { project: 'fontina' } }), false);
  assert.strictEqual(isClaimed({ tokens: {} }), false);
  assert.strictEqual(isClaimed({}), false);
  assert.strictEqual(isClaimed(undefined), false);
});

testAsync('a claimed workspace is never renamed', async () => {
  // herdr's tokens are one flat map, so naming this would overwrite the
  // claiming plugin's own project/n and erase its sidebar row.
  const claimed = [{ workspace_id: 'w1', number: 1, label: 'OddOS',
    tokens: { role: 'dashboard', project: 'OddOS', n: '\u25c6' } }];
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans({ ...snapshot([agent()]), workspaces: claimed });
  assert.strictEqual(plans.length, 0, 'claimed workspace must be left alone');
});

testAsync('a claimed workspace gets no metadata written over it', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, id, tokens }); return true; } };
  const claimed = [{ workspace_id: 'w1', number: 1, label: 'OddOS',
    tokens: { role: 'dashboard', project: 'OddOS' } }];
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata({ ...snapshot([agent()]), workspaces: claimed });
  assert.strictEqual(sent.length, 0, 'would have overwritten the claiming plugin');
});

testAsync('the guard can be turned off', async () => {
  const claimed = [{ workspace_id: 'w1', number: 1, label: 'OddOS',
    tokens: { role: 'dashboard' } }];
  const n = new Namer({ cfg: cfg({ respectPluginRoles: false }), store: freshStore(), sinks: [] });
  const plans = await n.buildPlans({ ...snapshot([agent()]), workspaces: claimed });
  assert.ok(plans.length > 0, 'opting out should restore normal behaviour');
});

process.stdout.write('\nsetup\n');

function tmpConfig(body) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ns-cfg-'));
  const file = path.join(dir, 'config.toml');
  fs.writeFileSync(file, body);
  return file;
}

test('the blocks reference only tokens namesync publishes', () => {
  const text = setup.blocks();
  for (const t of ['$n', '$project', '$worktree', '$locked', '$stale', '$since', '$age']) {
    assert.ok(text.includes(t), 'missing ' + t);
  }
  // branch and git_status are herdr built-ins for Space rows; $branch is the
  // metadata one, needed because Agent rows have no built-in for it.
  assert.ok(text.includes('{ token = "$branch"') || text.includes('"$since"'));
  assert.ok(!/\$(state_age|role|foo)/.test(text), 'references a token we do not publish');
});

test('an existing layout is never overwritten', () => {
  const file = tmpConfig('[ui]\nsidebar_width = 30\n\n[ui.sidebar.agents]\nrows = [["state_icon"]]\n');
  const p = setup.plan(file);
  assert.strictEqual(p.action, 'present');
  assert.deepStrictEqual(p.sections, ['ui.sidebar.agents']);
});

test('a config without sidebar rows is appendable', () => {
  const file = tmpConfig('[ui]\nsidebar_width = 30\n');
  assert.strictEqual(setup.plan(file).action, 'append');
});

test('a missing config is reported, not created', () => {
  const p = setup.plan(path.join(os.tmpdir(), 'ns-does-not-exist', 'config.toml'));
  assert.strictEqual(p.action, 'missing');
});

test('writing backs up first and appends valid TOML', () => {
  const before = '[ui]\nsidebar_width = 30\n';
  const file = tmpConfig(before);
  const backup = setup.write(file, setup.blocks());

  assert.strictEqual(fs.readFileSync(backup, 'utf8'), before, 'backup must be the original');
  const after = fs.readFileSync(file, 'utf8');
  assert.ok(after.startsWith(before), 'existing config must be preserved');
  assert.ok(after.includes('[ui.sidebar.agents]'));
  assert.ok(after.includes('[ui.sidebar.spaces]'));
  // and the result is now recognised as configured, so a second run declines
  assert.strictEqual(setup.plan(file).action, 'present');
});

test('sections are matched as headers, not as substrings', () => {
  // A comment mentioning the section must not count as having configured it.
  const file = tmpConfig('# see [ui.sidebar.agents] in the docs\n[ui]\n');
  assert.strictEqual(setup.plan(file).action, 'append');
});

process.stdout.write('\nvisible locks\n');

test('a lock remembers the label it was protecting, and when', () => {
  const st = freshStore();
  st.lock('w1', 'edited by hand', 'code quality');
  const info = st.lockInfo('w1');
  assert.strictEqual(info.label, 'code quality');
  assert.strictEqual(info.reason, 'edited by hand');
  assert.ok(info.at > 0);
});

test('re-locking keeps the original label and timestamp', () => {
  // Otherwise "held 1d" would reset to "held now" on every sync.
  const st = freshStore();
  st.lock('w1', 'edited by hand', 'code quality');
  const first = st.lockInfo('w1').at;
  st.lock('w1', 'edited by hand', 'something else');
  assert.strictEqual(st.lockInfo('w1').label, 'code quality');
  assert.strictEqual(st.lockInfo('w1').at, first);
});

testAsync('a held workspace is marked in its metadata', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, id, tokens }); return true; } };
  const store = freshStore();
  store.lock('w1', 'edited by hand', 'code quality');
  const n = new Namer({ cfg: cfg(), store, sinks: [sink] });
  await n.publishMetadata(snapshot([agent()]));
  const ws = sent.find((x) => x.kind === 'workspace');
  const pane = sent.find((x) => x.kind === 'pane');
  assert.strictEqual(ws.tokens.locked, 'held', 'the sidebar could not show it');
  assert.strictEqual(pane.tokens.locked, 'held');
});

testAsync('an unheld workspace carries no marker', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push(tokens); return true; } };
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [sink] });
  await n.publishMetadata(snapshot([agent()]));
  assert.strictEqual(sent[0].locked, null);
});

process.stdout.write('\nstale titles\n');

test('titleSeen counts transitions since the title last changed', () => {
  const st = freshStore();
  assert.deepStrictEqual(st.titleSeen('w1:p1', 'Fix auth', 10, 1000),
    { at: 1000, turns: 0, changed: true });
  // Same title, four transitions later.
  assert.deepStrictEqual(st.titleSeen('w1:p1', 'Fix auth', 14, 2000),
    { at: 1000, turns: 4, changed: false });
  // A new title resets both the clock and the transition baseline.
  assert.deepStrictEqual(st.titleSeen('w1:p1', 'Postgres tuning', 20, 3000),
    { at: 3000, turns: 0, changed: true });
});

test('a sequence going backwards never yields negative turns', () => {
  // herdr restarts reset the counter; that must not read as fresh.
  const st = freshStore();
  st.titleSeen('w1:p1', 'Fix auth', 100, 1000);
  assert.strictEqual(st.titleSeen('w1:p1', 'Fix auth', 3, 2000).turns, 0);
});

testAsync('a title held across many turns is flagged, and only then', async () => {
  const mk = async (seqs) => {
    const sent = [];
    const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
      reportMetadata: async (kind, id, tokens) => { sent.push({ kind, tokens }); return true; } };
    const store = freshStore();
    const n = new Namer({ cfg: cfg(), store, sinks: [sink] });
    for (const seq of seqs) {
      store.setMetadata('pane:w1:p1', ''); // force a republish each round
      store.setMetadata('workspace:w1', '');
      await n.publishMetadata(snapshot([agent({ state_change_seq: seq })]));
    }
    return sent[sent.length - 1].tokens.stale;
  };
  assert.strictEqual(await mk([1, 3]), null, 'two turns is not stale');
  assert.strictEqual(await mk([1, 9]), 'stale', 'eight turns is');
});

testAsync('stale detection can be turned off', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push(tokens); return true; } };
  const store = freshStore();
  const n = new Namer({ cfg: cfg({ showStale: false }), store, sinks: [sink] });
  await n.publishMetadata(snapshot([agent({ state_change_seq: 1 })]));
  store.setMetadata('pane:w1:p1', ''); store.setMetadata('workspace:w1', '');
  await n.publishMetadata(snapshot([agent({ state_change_seq: 99 })]));
  assert.strictEqual(sent[sent.length - 1].stale, null);
});

process.stdout.write('\nclearing a name\n');

test('clearing a held name hands the workspace back', () => {
  const st = freshStore();
  st.lock('w1', 'edited by hand', 'code quality');
  const r = decide({
    kind: 'workspace', id: 'w1', cfg: cfg(), store: st, agentStatus: 'working',
    context: { repo: 'app' }, current: '',
    desired: 'Fix auth middleware', intent: 'Fix auth middleware',
  });
  assert.strictEqual(r.rename, true, 'a cleared name must not stay held');
  assert.strictEqual(r.shouldRelease, true);
});

test('a hold still stands against any other edit', () => {
  const st = freshStore();
  st.lock('w1', 'edited by hand', 'code quality');
  const held = (current) => decide({
    kind: 'workspace', id: 'w1', cfg: cfg(), store: st, agentStatus: 'working',
    context: { repo: 'app' }, current,
    desired: 'Fix auth middleware', intent: 'Fix auth middleware',
  });
  assert.strictEqual(held('code quality').reason, SKIP.LOCKED);
  assert.strictEqual(held('something else').reason, SKIP.LOCKED);
  // whitespace is still empty
  assert.strictEqual(held('   ').shouldRelease, true);
});

testAsync('applying a release actually clears the hold, and persists it', async () => {
  const store = freshStore();
  store.lock('w1', 'edited by hand', 'code quality');
  const n = new Namer({ cfg: cfg(), store, sinks: [{ name: 'herdr',
    kinds: ['workspace', 'tab', 'agent'], apply: async () => true }] });
  await n.apply([{ kind: 'workspace', id: 'w1', current: '', desired: 'Fix auth',
    verdict: { rename: true, shouldRelease: true } }]);
  assert.strictEqual(store.isLocked('w1'), false, 'hold survived the release');
  assert.strictEqual(new Store(store.file).isLocked('w1'), false, 'release was not saved');
});

process.stdout.write('\nintent age\n');

testAsync('$age tracks the intent, $since tracks the state', async () => {
  const sent = [];
  const sink = { name: 'herdr', kinds: ['workspace', 'tab', 'agent'], apply: async () => true,
    reportMetadata: async (kind, id, tokens) => { sent.push({ kind, tokens }); return true; } };
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [sink] });

  // Same title throughout; the agent changes state twice.
  await n.publishMetadata(snapshot([agent({ agent_status: 'working', state_change_seq: 1 })]));
  const first = sent.find((x) => x.kind === 'workspace').tokens;
  assert.strictEqual(first.age, 'now');
  assert.strictEqual(first.since, 'now');

  // Age is measured from when the title changed, so a state change does not
  // reset it. Both read 'now' here because no time has passed -- what matters
  // is that they come from different clocks.
  store.setMetadata('workspace:w1', ''); store.setMetadata('pane:w1:p1', '');
  await n.publishMetadata(snapshot([agent({ agent_status: 'idle', state_change_seq: 2 })]));
  const second = sent.find((x) => x.kind === 'workspace' && x !== sent[0]).tokens;
  assert.ok('age' in second && 'since' in second);
});

test('the two clocks answer different questions', () => {
  const st = freshStore();
  const t0 = 1000000;
  // Title set once, then two state transitions over ten minutes.
  st.titleSeen('w1:p1', 'Fix auth', 1, t0);
  st.stateAt('w1:p1', 'working', t0);
  st.stateAt('w1:p1', 'idle', t0 + 9 * 60000);

  const titleAt = st.titleSeen('w1:p1', 'Fix auth', 3, t0 + 10 * 60000).at;
  const stateAt = st.stateAt('w1:p1', 'idle', t0 + 10 * 60000).at;

  // age counts from the title; since counts from the last transition.
  assert.strictEqual(naming.formatSince(t0 + 10 * 60000 - titleAt), '10m');
  assert.strictEqual(naming.formatSince(t0 + 10 * 60000 - stateAt), '1m');
});

process.stdout.write('\nfolder is the last resort\n');

testAsync('a path that no longer exists still resolves to the repository', async () => {
  // A deleted worktree: every git query against the path fails, so detection
  // walks up. The directory it lands on has a remote, and that remote is the
  // answer -- not the folder it happens to be sitting in.
  const { detectProject, gitCache } = require('../src/namer');
  gitCache.clear();
  const repo = path.join(__dirname, '..');
  const gone = path.join(repo, '.does-not-exist', 'deep', 'gone');
  const viaGone = await detectProject(gone);
  const direct = await detectProject(repo);
  assert.strictEqual(viaGone, direct,
    'walking up should reach the same identity as asking the root directly');
});

testAsync('a manifest name beats the folder it lives in', async () => {
  const { detectProject, gitCache } = require('../src/namer');
  gitCache.clear();
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'ns-folder-'));
  fs.writeFileSync(path.join(dir, 'package.json'), '{"name":"declared-name"}');
  assert.strictEqual(await detectProject(dir), 'declared-name');
  assert.notStrictEqual(await detectProject(dir), path.basename(dir));
});

process.stdout.write('\nsources\n');

testAsync('the title source returns the agent\'s own title', async () => {
  const src = createTitleSource();
  assert.strictEqual(await src.observe({ agent: agent() }), 'Fix auth middleware');
  // The stripped title is preferred, and the glyph is gone either way.
  assert.strictEqual(
    await src.observe({ agent: { terminal_title: '\u25d1 Fix auth middleware' } }),
    'Fix auth middleware');
  assert.strictEqual(await src.observe({ agent: {} }), '');
});

testAsync('title is enabled by default and can be turned off', async () => {
  assert.deepStrictEqual((await resolveSources(cfg())).map((s) => s.name), ['title']);
  assert.deepStrictEqual(
    (await resolveSources(cfg({ sources: { title: { enabled: false } } }))).map((s) => s.name),
    []);
});

testAsync('the first source with an answer wins', async () => {
  const asked = [];
  const quiet = { name: 'quiet', observe: async () => { asked.push('quiet'); return ''; } };
  const loud = { name: 'loud', observe: async () => { asked.push('loud'); return 'a real answer'; } };
  const never = { name: 'never', observe: async () => { asked.push('never'); return 'too late'; } };

  const r = await observe([quiet, loud, never], {});
  assert.strictEqual(r.intent, 'a real answer');
  assert.strictEqual(r.source, 'loud');
  assert.deepStrictEqual(asked, ['quiet', 'loud'], 'a later source should not be consulted');
});

testAsync('a source that throws is skipped, not fatal', async () => {
  // An observation failing is not a reason to stop naming the whole session.
  const broken = { name: 'broken', observe: async () => { throw new Error('nope'); } };
  const warned = [];
  const r = await observe([broken, createTitleSource()],
    { agent: agent() }, (lvl, msg) => warned.push(msg));
  assert.strictEqual(r.intent, 'Fix auth middleware');
  assert.ok(warned.some((w) => w.includes('broken')), 'the failure should be logged');
});

testAsync('no source with an answer means no name, not a crash', async () => {
  const r = await observe([{ name: 'quiet', observe: async () => null }], {});
  assert.strictEqual(r.intent, '');
  assert.strictEqual(r.source, null);
});

testAsync('a custom source flows through the policy like any other', async () => {
  // The point of the seam: where a name comes from changes nothing about
  // whether it is allowed to be applied.
  const custom = { name: 'custom', observe: async () => 'Postgres index tuning' };
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [], sources: [custom] });
  const plans = await n.buildPlans(snapshot([agent()]));
  const ws = plans.find((p) => p.kind === 'workspace');
  assert.strictEqual(ws.desired, 'Postgres index tuning');
  assert.strictEqual(ws.verdict.rename, true);
});

testAsync('a held workspace ignores a custom source too', async () => {
  const custom = { name: 'custom', observe: async () => 'Postgres index tuning' };
  const store = freshStore();
  store.lock('w1', 'edited by hand', 'code quality');
  const n = new Namer({ cfg: cfg(), store, sinks: [], sources: [custom] });
  const plans = await n.buildPlans(snapshot([agent()]));
  const ws = plans.find((p) => p.kind === 'workspace');
  assert.strictEqual(ws.verdict.rename, false, 'a source must not override a hold');
});

process.stdout.write('\nlooking harder\n');

// A source that records every time it is consulted, so the gate can be
// observed rather than inferred.
function countingCostly(answer = 'from the expensive one') {
  const calls = [];
  return { source: { name: 'costly', costly: true,
    observe: async () => { calls.push(Date.now()); return answer; } }, calls };
}

testAsync('a costly source is skipped while the title is fresh', async () => {
  const { source, calls } = countingCostly();
  const n = new Namer({ cfg: cfg(), store: freshStore(), sinks: [],
    sources: [source, createTitleSource()] });
  await n.buildPlans(snapshot([agent({ agent_status: 'idle', state_change_seq: 1 })]));
  assert.strictEqual(calls.length, 0, 'nothing had failed yet');
});

testAsync('a costly source is skipped while the agent is mid-turn', async () => {
  const { source, calls } = countingCostly();
  const store = freshStore();
  // Make the title stale first.
  store.titleSeen('w1:p1', 'Fix auth middleware', 1, Date.now());
  const n = new Namer({ cfg: cfg(), store, sinks: [], sources: [source, createTitleSource()] });
  await n.buildPlans(snapshot([agent({ agent_status: 'working', state_change_seq: 99 })]));
  assert.strictEqual(calls.length, 0, 'the pane is half-written mid-turn');
});

testAsync('a costly source is consulted once the title has gone stale', async () => {
  const { source, calls } = countingCostly();
  const store = freshStore();
  store.titleSeen('w1:p1', 'Fix auth middleware', 1, Date.now());
  const n = new Namer({ cfg: cfg(), store, sinks: [], sources: [source, createTitleSource()] });
  const plans = await n.buildPlans(snapshot([agent({ agent_status: 'idle', state_change_seq: 99 })]));
  assert.strictEqual(calls.length, 1, 'the free answer had demonstrably failed');
  assert.strictEqual(plans.find((p) => p.kind === 'workspace').desired,
    'from the expensive one');
});

testAsync('the floor stops a repeatedly-finishing session billing in a loop', async () => {
  const { source, calls } = countingCostly();
  const store = freshStore();
  store.titleSeen('w1:p1', 'Fix auth middleware', 1, Date.now());
  const n = new Namer({ cfg: cfg(), store, sinks: [], sources: [source, createTitleSource()] });
  const snap = snapshot([agent({ agent_status: 'idle', state_change_seq: 99 })]);
  await n.buildPlans(snap);
  await n.buildPlans(snap);
  await n.buildPlans(snap);
  assert.strictEqual(calls.length, 1, 'consulted again inside the floor');
});

testAsync('a cheap answer does not postpone the next real attempt', async () => {
  // Only an actual consultation charges the floor.
  const { source, calls } = countingCostly();
  const store = freshStore();
  const n = new Namer({ cfg: cfg(), store, sinks: [], sources: [createTitleSource(), source] });
  await n.buildPlans(snapshot([agent({ agent_status: 'idle', state_change_seq: 1 })]));
  assert.strictEqual(store.lastDeep('w1:p1'), 0, 'the floor was charged for nothing');
  assert.strictEqual(calls.length, 0);
});

testAsync('costly sources can be switched off entirely', async () => {
  const { source, calls } = countingCostly();
  const store = freshStore();
  store.titleSeen('w1:p1', 'Fix auth middleware', 1, Date.now());
  const n = new Namer({ cfg: cfg({ consultCostlySources: false }), store, sinks: [],
    sources: [source, createTitleSource()] });
  await n.buildPlans(snapshot([agent({ agent_status: 'idle', state_change_seq: 99 })]));
  assert.strictEqual(calls.length, 0);
});

process.stdout.write('\nreading a pane\n');

// A screenful from a real agent, chrome and all.
const SCREEN = [
  '\u256d\u2500 something \u2500\u256e',
  '',
  '\u23fa Running 1 shell command \u00b7 1m 7s\u2026',
  '  \u23bf  $ bash -n scripts/preflight && echo "syntax ok"',
  '\u2726 Tomfoolering\u2026 (29m 22s \u00b7 \u2193 64.1k tokens)',
  '\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500',
  '\u276f ',
  '  Opus 5 (1M context) \u00b7 ~/Code/perfect \u00b7  item-0021-memory-bar* \u00b7 78% ctx \u00b7 $393.47      /rc',
  '  \u23f5\u23f5 bypass permissions on (shift+tab to cycle) \u00b7 \u2190 for agents',
].join('\n');

test('cleaning keeps the work and drops the furniture', () => {
  const body = viewport.clean(SCREEN);
  assert.ok(body.some((l) => l.includes('bash -n scripts/preflight')), 'lost the command');
  assert.ok(!body.some((l) => l.includes('Tomfoolering')), 'kept the spinner');
  assert.ok(!body.some((l) => /^[\u2500\u2501]+$/.test(l)), 'kept a ruler');
  assert.ok(!body.some((l) => l.includes('bypass permissions')), 'kept the mode line');
  assert.ok(!body.some((l) => l === ''), 'kept a blank line');
});

test('the status line is chrome, so location is read before cleaning', () => {
  // It ends with the same slash-command hint the chrome filter matches on, so
  // cleaning removes it -- and it carries the one durable fact on screen.
  assert.strictEqual(viewport.locationFrom(SCREEN.split('\n')), 'Code perfect');
  assert.strictEqual(viewport.clean(SCREEN).some((l) => l.includes('Opus 5')), false);
});

test('a location is not an intent, which is why this is not a source', () => {
  // Recorded so the conclusion survives the reasoning: measured against six
  // live agents, every guess was worse than the title it would have replaced.
  const location = viewport.locationFrom(SCREEN.split('\n'));
  assert.strictEqual(location, 'Code perfect');
  assert.ok(!/[a-z]+ing\b/.test(location), 'a location never describes work');
});

testAsync('reading a pane that is not there yields nothing, not a throw', async () => {
  assert.deepStrictEqual(await viewport.readPane(null, 'w1:p1'), { body: [], raw: [] });
  assert.deepStrictEqual(await viewport.readPane({}, null), { body: [], raw: [] });
});

process.stdout.write('\nasking a model\n');

// A stand-in for anything speaking the chat-completions shape.
function stubModel(reply, { status = 200, delayMs = 0 } = {}) {
  const seen = [];
  const server = http.createServer((req, res) => {
    let raw = '';
    req.on('data', (c) => { raw += c; });
    req.on('end', () => {
      seen.push({ auth: req.headers.authorization, body: JSON.parse(raw) });
      setTimeout(() => {
        res.writeHead(status, { 'content-type': 'application/json' });
        res.end(JSON.stringify({ choices: [{ message: { content: reply } }] }));
      }, delayMs);
    });
  });
  return new Promise((resolve) => {
    server.listen(0, '127.0.0.1', () => resolve({
      server, seen,
      url: 'http://127.0.0.1:' + server.address().port + '/v1/chat/completions',
    }));
  });
}

// A client that returns a fixed pane screenful.
const paneClient = (text) => ({ request: async () => ({ read: { text } }) });
const SCREEN_TEXT = 'Ran 3 shell commands\n\u23fa The macOS test was never added; adding it now';

test('a model answer is scrutinised like any other name', () => {
  assert.strictEqual(usable('Fix worktree detection'), 'Fix worktree detection');
  assert.strictEqual(usable('"Fix worktree detection."'), 'Fix worktree detection');
  assert.strictEqual(usable('unknown'), '', 'the escape hatch must not become a name');
  assert.strictEqual(usable(''), '');
  assert.strictEqual(usable('I am sorry, I cannot determine that'), '',
    'a model explaining itself is not a label');
  assert.strictEqual(usable('Based on the screen it appears to be'), '');
  assert.strictEqual(usable('a b c d e f g h i j'), '', 'too many words');
});

testAsync('it sends the cleaned pane and returns a usable label', async () => {
  const { server, seen, url } = await stubModel('Fix worktree branch detection');
  try {
    const src = createLlmSource({ enabled: true, endpoint: url, model: 'test-model' }, {});
    const answer = await src.observe({
      client: paneClient(SCREEN_TEXT), agent: { pane_id: 'w1:p1' },
    });
    assert.strictEqual(answer, 'Fix worktree branch detection');
    assert.strictEqual(seen.length, 1);
    assert.strictEqual(seen[0].body.model, 'test-model');
    assert.strictEqual(seen[0].body.temperature, 0, 'one screen should give one name');
    assert.ok(seen[0].body.messages[1].content.includes('macOS test'),
      'the pane content should reach the model');
  } finally { server.close(); }
});

testAsync('the key comes from the environment, never from config', async () => {
  const { server, seen, url } = await stubModel('Fix the parser');
  try {
    process.env.NS_TEST_KEY = 'secret-value';
    const src = createLlmSource(
      { enabled: true, endpoint: url, model: 'm', apiKeyEnv: 'NS_TEST_KEY' }, {});
    await src.observe({ client: paneClient(SCREEN_TEXT), agent: { pane_id: 'w1:p1' } });
    assert.strictEqual(seen[0].auth, 'Bearer secret-value');
  } finally { server.close(); delete process.env.NS_TEST_KEY; }
});

testAsync('an endpoint that errors is skipped, not fatal', async () => {
  const { server, url } = await stubModel('nope', { status: 500 });
  try {
    const src = createLlmSource({ enabled: true, endpoint: url, model: 'm' }, {});
    const warned = [];
    const r = await observe([src, createTitleSource()],
      { client: paneClient(SCREEN_TEXT), agent: agent(), deep: true },
      (lvl, msg) => warned.push(msg));
    assert.strictEqual(r.intent, 'Fix auth middleware', 'should fall back to the title');
    assert.ok(warned.some((w) => w.includes('llm')));
  } finally { server.close(); }
});

testAsync('a slow endpoint gives up rather than holding the sync', async () => {
  const { server, url } = await stubModel('too late', { delayMs: 400 });
  try {
    const src = createLlmSource(
      { enabled: true, endpoint: url, model: 'm', timeoutMs: 50 }, {});
    await assert.rejects(() => src.observe({
      client: paneClient(SCREEN_TEXT), agent: { pane_id: 'w1:p1' },
    }));
  } finally { server.close(); }
});

testAsync('a generated name has no more authority than a title', async () => {
  // The whole safety argument: expensive does not mean exempt.
  const { server, url } = await stubModel('Postgres index tuning');
  try {
    const src = createLlmSource({ enabled: true, endpoint: url, model: 'm' }, {});
    const store = freshStore();
    store.lock('w1', 'edited by hand', 'code quality');
    store.titleSeen('w1:p1', 'Fix auth middleware', 1, Date.now());
    const n = new Namer({ cfg: cfg(), store, sinks: [], sources: [src],
      client: paneClient(SCREEN_TEXT) });
    const plans = await n.buildPlans(snapshot([
      agent({ agent_status: 'idle', state_change_seq: 99 }),
    ]));
    const ws = plans.find((p) => p.kind === 'workspace');
    assert.strictEqual(ws.verdict.rename, false, 'a hold must survive a paid answer');
  } finally { server.close(); }
});

process.stdout.write('\nwhat the person asked for\n');

function tmpTranscript(entries) {
  const base = fs.mkdtempSync(path.join(os.tmpdir(), 'ns-tx-'));
  const project = path.join(base, '-Users-someone-Code-thing');
  fs.mkdirSync(project);
  const id = 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee';
  fs.writeFileSync(path.join(project, id + '.jsonl'),
    entries.map((e) => JSON.stringify(e)).join('\n'));
  return { root: base, id };
}
const said = (text) => ({ type: 'user', message: { content: text } });

test('the session id comes from herdr, so no hook is needed', () => {
  assert.strictEqual(transcript.sessionId({
    agent_session: { kind: 'id', value: 'abc-123' } }), 'abc-123');
  // Absent, or reported in some other shape, must be survivable.
  assert.strictEqual(transcript.sessionId({}), '');
  assert.strictEqual(transcript.sessionId({ agent_session: { kind: 'other' } }), '');
  assert.strictEqual(transcript.sessionId(undefined), '');
});

test('a transcript is found by session id, whatever the project folder', () => {
  const { root, id } = tmpTranscript([said('hello')]);
  assert.ok(transcript.findTranscript(id, root).endsWith(id + '.jsonl'));
  assert.strictEqual(transcript.findTranscript('no-such-id', root), '');
  assert.strictEqual(transcript.findTranscript('', root), '');
});

test('only things a person actually said are kept', () => {
  const { root, id } = tmpTranscript([
    said('first real ask'),
    { type: 'assistant', message: { content: 'a reply' } },
    said('<system-reminder>not spoken</system-reminder>'),
    said('[Request interrupted by user]'),
    said('This session is being continued from a previous conversation that ran out of context'),
    said('Caveat: The messages below were generated by the user while running local commands'),
    said('second real ask'),
  ]);
  const asks = transcript.recentAsks(transcript.findTranscript(id, root));
  assert.deepStrictEqual(asks, ['first real ask', 'second real ask']);
});

test('a missing or unreadable transcript yields nothing, not a throw', () => {
  assert.deepStrictEqual(transcript.recentAsks('/no/such/file.jsonl'), []);
  assert.deepStrictEqual(transcript.readAsks({}), []);
  assert.deepStrictEqual(transcript.readAsks(undefined), []);
});

testAsync('the model is given what was asked for, not the scrollback', async () => {
  const { server, seen, url } = await stubModel('Fix the toolchain');
  const { root, id } = tmpTranscript([said('fix the stable toolchain and continue')]);
  try {
    const src = createLlmSource(
      { enabled: true, endpoint: url, model: 'm', transcriptRoot: root }, {});
    const answer = await src.observe({
      client: paneClient('SCROLLBACK THAT SHOULD LOSE'),
      agent: { pane_id: 'w1:p1', agent_session: { kind: 'id', value: id } },
    });
    assert.strictEqual(answer, 'Fix the toolchain');
    const sent = seen[0].body.messages[1].content;
    assert.ok(sent.includes('fix the stable toolchain'), 'the ask should reach the model');
    assert.ok(!sent.includes('SCROLLBACK'), 'the pane should not have been used');
  } finally { server.close(); }
});

testAsync('with no session reported it falls back to the pane', async () => {
  const { server, seen, url } = await stubModel('Fix the parser');
  try {
    const src = createLlmSource(
      { enabled: true, endpoint: url, model: 'm', transcriptRoot: '/no/such/root' }, {});
    const answer = await src.observe({
      client: paneClient('Ran 3 shell commands\nAdding the macOS test now'),
      agent: { pane_id: 'w1:p1' },
    });
    assert.strictEqual(answer, 'Fix the parser');
    assert.ok(seen[0].body.messages[1].content.includes('macOS test'),
      'the pane is the documented fallback');
  } finally { server.close(); }
});

Promise.all(pending).then(() => {
  process.stdout.write('\n' + passed + ' passed, ' + failed + ' failed\n');
  process.exit(failed ? 1 : 0);
});
