'use strict';

// herdr agent names: [a-z][a-z0-9_-]{0,31}
const AGENT_NAME_MAX = 32;

// Words that survive in a title but carry no signal about what the work IS.
const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'for', 'to', 'of', 'in', 'on', 'at',
  'by', 'with', 'from', 'into', 'via', 'is', 'are', 'was', 'be', 'this', 'that',
  'it', 'its', 'my', 'our', 'your', 'some', 'new', 'up', 'out',
]);

function normalize(title) {
  return String(title == null ? '' : title)
    // Strip the agent state glyph herdr prefixes to raw titles, plus any
    // leading spinner braille that slipped through.
    .replace(/^[─-➿⠀-⣿-\s*]+/u, '')
    .replace(/\s+/g, ' ')
    .trim();
}

// Crude stemming only: enough that "plugin"/"plugins" and "rename"/"renaming"
// compare equal, so a reworded title does not count as a new intent.
function stem(word) {
  let w = word;
  if (w.length > 4 && w.endsWith('ing')) w = w.slice(0, -3);
  else if (w.length > 4 && w.endsWith('ed')) w = w.slice(0, -2);
  if (w.length > 3 && w.endsWith('es')) w = w.slice(0, -2);
  else if (w.length > 3 && w.endsWith('s') && !w.endsWith('ss')) w = w.slice(0, -1);
  // Collapse the silent -e so "rename" and "renaming" land on the same stem.
  if (w.length > 4 && w.endsWith('e')) w = w.slice(0, -1);
  return w;
}

function tokens(text) {
  return normalize(text)
    .toLowerCase()
    .split(/[^a-z0-9]+/)
    .filter((t) => t.length > 1 && !STOP_WORDS.has(t))
    .map(stem);
}

function slugify(text, max = AGENT_NAME_MAX) {
  let s = normalize(text)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  if (!s) return '';
  // Must start with a letter.
  if (!/^[a-z]/.test(s)) s = 'x-' + s;
  if (s.length > max) {
    s = s.slice(0, max);
    // Prefer cutting at a word boundary over mid-word, when one is close.
    const cut = s.lastIndexOf('-');
    if (cut >= Math.floor(max * 0.6)) s = s.slice(0, cut);
  }
  return s.replace(/-+$/g, '');
}

// Jaccard overlap of significant tokens. 1 = same intent, 0 = unrelated.
function similarity(a, b) {
  const A = new Set(tokens(a));
  const B = new Set(tokens(b));
  if (!A.size && !B.size) return 1;
  if (!A.size || !B.size) return 0;
  let shared = 0;
  for (const t of A) if (B.has(t)) shared += 1;
  return shared / (A.size + B.size - shared);
}

// Commands a pane shows as its title before an agent takes over.
const COMMAND_VERBS = new RegExp(
  '^(cd|ls|ll|cat|tail|head|less|man|git|gh|npm|npx|pnpm|yarn|bun|node|deno|'
  + 'python|python3|pip|cargo|rustc|go|make|just|docker|kubectl|ssh|scp|sudo|'
  + 'brew|apt|vim|nvim|emacs|hx|code|claude|codex|pi|tmux|herdr|clear|exit)\\b',
);

// True when the title says nothing about intent and should never become a name.
function isJunkTitle(title, cfg, context = {}) {
  const t = normalize(title);
  if (!t) return true;
  const lower = t.toLowerCase();

  if ((cfg.ignoreTitles || []).some((x) => lower === String(x).toLowerCase())) return true;

  // A shell prompt: "oddurs@Oddurs-MacBook-Pro:~/Code/perfect".
  if (/^\S+@\S+:/.test(t)) return true;

  // A bare path or filename is location, not intent.
  if (/^[~/.]/.test(t) || /^[a-z]:[\\/]/i.test(t)) return true;

  // A command line the shell echoed before the agent started:
  // "cd namesync", "claude --dangerously-skip-permissions".
  // The verb alone is not enough: "go", "make", "node", "less" and "man" are
  // ordinary words, and "go routine leak fix" is a perfectly good intent.
  // Require the title to also LOOK like an invocation — short, or carrying a
  // flag, path or assignment.
  if (COMMAND_VERBS.test(t)) {
    const words = t.split(/\s+/);
    if (words.length <= 2 || /\s--?[a-z]/i.test(t) || /[/~=]/.test(t)) return true;
  }
  if (/\s--[a-z]/.test(t)) return true;

  // The repo name alone is what herdr already defaults to.
  if (context.repo && lower === String(context.repo).toLowerCase()) return true;

  // Needs at least one real word.
  if (!tokens(t).length) return true;
  return false;
}

// Distinguishes a label a human chose from the one herdr generated for a new
// workspace or tab. Without this, every fresh workspace would look "manually
// named" and the plugin would never claim it.
function looksAutoGenerated(name, context = {}) {
  const t = normalize(name);
  if (!t) return true;
  const lower = t.toLowerCase();

  /* Anything that merely restates where the workspace lives, or what the
     project is called, is not a description of work. herdr labels a new
     workspace from its directory, and its rename dialog appears to put a
     directory name back when a name is cleared -- so these have to be
     recognised as "nobody chose this" or the workspace gets held for good on
     the strength of a name the user was trying to remove. */
  const defaults = [context.project, context.repo, context.dirName,
    context.paneDir, context.foregroundDir, context.branch]
    .filter(Boolean)
    .map((x) => String(x).toLowerCase());
  if (defaults.includes(lower)) return true;

  // herdr's own placeholders: "w3", "tab 2", "shell", bare numbers.
  if (/^w\d+(:t\d+)?$/.test(lower)) return true;
  if (/^(tab|window|pane|workspace|shell|terminal)\s*\d*$/.test(lower)) return true;
  if (/^\d+$/.test(lower)) return true;

  return false;
}

// Drops a leading project name from an intent, so a row already labelled
// "ptop" does not read "ptop-adopt-remaining-lessons" underneath it. Never
// strips everything: "cairn" under "cairn" stays as it is.
function stripProject(text, project) {
  const t = normalize(text);
  if (!t || !project) return t;
  const esc = String(project).replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const stripped = t.replace(new RegExp('^' + esc + '[\\s:_/-]+', 'i'), '').trim();
  if (!stripped || !tokens(stripped).length) return t;
  // Nothing was removed, so there is nothing to re-case. Capitalising here
  // would quietly rewrite the first letter of every lowercase title.
  if (stripped === t) return t;
  return stripped.charAt(0).toUpperCase() + stripped.slice(1);
}

// Coarse on purpose. A per-second clock would republish metadata constantly
// for a value nobody reads that precisely; buckets mean the token only changes
// a handful of times an hour, and the dedup in publishMetadata does the rest.
function formatSince(ms) {
  if (!Number.isFinite(ms) || ms < 45000) return 'now';
  const minutes = Math.round(ms / 60000);

  // Minute precision only while it is worth watching. After that the value
  // steps, because every step is a metadata write and a sidebar redraw for
  // every agent -- ten agents ticking over a minute counter is ten rewrites a
  // minute for a number nobody reads that closely.
  if (minutes < 10) return minutes + 'm';
  if (minutes < 60) return (Math.floor(minutes / 5) * 5) + 'm';

  const hours = Math.floor(minutes / 60);
  if (hours < 24) return hours + 'h';
  return Math.floor(hours / 24) + 'd';
}

function render(template, vars) {
  return String(template)
    .replace(/\{([a-z-]+)\}/g, (m, key) => (vars[key] == null ? '' : String(vars[key])))
    .replace(/\s+/g, ' ')
    .trim();
}

// Agent names must be unique among live agents; suffix on collision.
function uniqueAgentName(desired, taken) {
  if (!desired) return '';
  if (!taken.has(desired)) return desired;
  for (let i = 2; i < 100; i += 1) {
    const suffix = '-' + i;
    const base = desired.slice(0, AGENT_NAME_MAX - suffix.length).replace(/-+$/g, '');
    const candidate = base + suffix;
    if (!taken.has(candidate)) return candidate;
  }
  return '';
}

module.exports = {
  normalize, tokens, stem, slugify, stripProject, formatSince, looksAutoGenerated, similarity, isJunkTitle, render,
  uniqueAgentName, AGENT_NAME_MAX, STOP_WORDS,
};
