'use strict';
const { similarity, isJunkTitle, normalize, looksAutoGenerated } = require('./naming');

// Every reason a rename can be declined, so `status` and the log can explain
// themselves instead of silently doing nothing.
const SKIP = {
  DISABLED: 'plugin disabled',
  NO_INTENT: 'title carries no intent',
  JUNK: 'title is a shell, path or bare repo name',
  LOCKED: 'name locked (edited by hand)',
  MANUAL: 'current name was set by hand',
  BLOCKED: 'agent is waiting on a dialog',
  UNCHANGED: 'name already matches',
  SIMILAR: 'same intent, only reworded',
  RATE_LIMITED: 'renamed too recently',
  MULTI_AGENT: 'workspace holds several agents',
};

// Decides whether `desired` should replace `current` for one target.
// Pure: no I/O, so it is straightforward to test.
function decide({ kind, id, current, desired, intent, cfg, store, now = Date.now(),
  agentStatus, context = {}, force = false }) {
  if (!cfg.enabled) return { rename: false, reason: SKIP.DISABLED };
  if (!intent || !normalize(intent)) return { rename: false, reason: SKIP.NO_INTENT };
  if (isJunkTitle(intent, cfg, context)) return { rename: false, reason: SKIP.JUNK };
  if (!desired) return { rename: false, reason: SKIP.NO_INTENT };

  // A blocked agent's title describes the dialog, not the work. No event is
  // guaranteed when it unblocks, so ask the caller to look again shortly.
  if (cfg.skipWhileBlocked && agentStatus === 'blocked') {
    return { rename: false, reason: SKIP.BLOCKED, retryInMs: 5000 };
  }

  if (store.isLocked(id)) return { rename: false, reason: SKIP.LOCKED };

  const cur = normalize(current);
  if (cur === normalize(desired)) return { rename: false, reason: SKIP.UNCHANGED };

  // The heart of "rename only when it makes sense": if the live name is not
  // the one we last wrote, a human changed it. Back off permanently.
  // A label herdr generated itself (the directory name, "w3", "tab 2") is
  // nobody's choice, so it stays adoptable.
  if (cfg.respectManualNames && cur && !looksAutoGenerated(cur, context)) {
    const ours = store.authored(kind, id);
    if (ours == null || normalize(ours) !== cur) {
      return { rename: false, reason: SKIP.MANUAL, shouldLock: true };
    }
  }

  // force skips the anti-churn guards below — rate limit and similarity —
  // because those exist to ignore the AGENT rewording itself, not to block a
  // change the user just asked for. Locks, hand-edits, junk and blocked
  // agents are still respected above.
  if (force) return { rename: true, reason: 'forced' };

  const elapsed = now - store.lastRenameAt(id);
  if (elapsed < cfg.minRenameIntervalMs) {
    return { rename: false, reason: SKIP.RATE_LIMITED, retryInMs: cfg.minRenameIntervalMs - elapsed };
  }

  // A reworded title describing the same work is not a new intent.
  if (cur && similarity(cur, desired) >= cfg.similarityThreshold) {
    return { rename: false, reason: SKIP.SIMILAR };
  }

  return { rename: true, reason: 'intent changed' };
}

module.exports = { decide, SKIP };
